FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    sudo build-essential git curl python3 debootstrap qemu-utils \
    flex bison libncurses-dev libssl-dev bc \
    libelf-dev libdw-dev

RUN FC_VERSION="1.7.0" && \
    curl -sL https://github.com/firecracker-microvm/firecracker/releases/download/v${FC_VERSION}/firecracker-v${FC_VERSION}-x86_64.tgz | tar -xz && \
    mv release-v${FC_VERSION}-x86_64/firecracker-v${FC_VERSION}-x86_64 /usr/local/bin/firecracker && \
    chmod +x /usr/local/bin/firecracker

WORKDIR /app
COPY . .

RUN chmod +x build/*.sh vm/*.sh rootfs/* setup-runtime.sh 2>/dev/null || true


CMD ["/bin/bash"]