services:
  hardhat:
    image: node:20.19.5
    container_name: dnat-hardhat
    working_dir: /app
    volumes:
      - ../smart-contract:/app
    ports:
      - "8545:8545"
    command: ["sh", "-c", "npm install && npx hardhat node --hostname 0.0.0.0"]

  ipfs:
    image: ipfs/kubo:latest
    container_name: dnat-ipfs
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ipfs_data:/data/ipfs
    environment:
      - IPFS_PROFILE=server

volumes:
  ipfs_data:
